version: '3.9'
services:
  database:
    image: mariadb
    container_name: ${SQL_NAME}
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT}
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
      MYSQL_PASSWORD: ${MYSQL_PASS}
    volumes:
            - $PWD/db:/var/lib/mysql
    networks:
      - lan 

  nextcloud:
    image: nextcloud
    restart: unless-stopped
    container_name: ${NX_NAME}
    environment:
      MYSQL_HOST: "database"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
      MYSQL_PASSWORD: ${MYSQL_PASS}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_ADMIN_USER: "igloonet"
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_URL}

    mem_limit: ${MEM_LIMIT}
    mem_reservation: ${MEM_RESERVATION}
    cpus: $CPU_LIMIT

    networks:
      - lan
      - traefik_web
    volumes:
            - $PWD/html:/var/www/html
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.rule: 'Host(`${NEXTCLOUD_URL}`)'
      traefik.http.services.nextcloud.loadbalancer.server.port: 80
      

networks:
  traefik_web:
    external: true
    
  lan:
