version: '3.7'
services:
  database:
    image: mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
      MYSQL_PASSWORD_FILE: './secrets/mysql-password'
    networks:
      - lan 
    volumes: 
      - db:/var/lib/mysql

  nextcloud:
    depends_on:
      - database
    image: nextcloud:latest
    restart: unless-stopped
    environment:
      MYSQL_HOST: 'database'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: "nextcloud"
      MYSQL_PASSWORD_FILE: './secrets/mysql-password'
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_ADMIN_USER: igloonet
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_URL}
    networks:
      - lan
      - traefik_web
    volumes:
      - html:/var/www/html
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.rule: 'Host(`${NEXTCLOUD_URL}`)'
      traefik.http.services.nextcloud.loadbalancer.server.port: 80
      
volumes:
  db:
  html:

networks:
  traefik_web:
    external: true
    
  lan:
